defaults:
  - _self_
  - problem: Fluid Mechanics
  - override hydra/output: local

hydra:
  job:
    name: ${problem.name}
    chdir: True

method: mcts  # 可选: bfsearch, mcts
dataset_path: pix/data/Untitled_v_up_2_v_bottom_2_ggg_9.81_2d_grid.npz
#
verbose: True
n_jobs: 10

# For MCTS
exploration_weight: 1.0 
epsilon: 0.05           
max_rollout: 30
time_limit: 3600
verbose_level: 2