defaults:
  - _self_
  - problem: Fluid Mechanics
  - override hydra/output: local

hydra:
  job:
    name: ${problem.name}
    chdir: True

method: mcts  # 可选: bfsearch, mcts
dataset_path: pix/data/4Untitled_v_up_0.5_v_bottom_0.5_ggg_0_2d_grid.npz

coefficient_optimizer: "scipy" # Options: scipy, pinn
pinn_config:
  epochs: 100
  learning_rate: 1e-3
  pde_loss_weight: 0.01

verbose: True
n_jobs: 10

# For MCTS
exploration_weight: 1.0 
epsilon: 0.05           
max_rollout: 30
time_limit: 3600
verbose_level: 2

use_hippylib: False

# For SR
use_snip: False
snip_ckpt: /sfs/xcy/snip-e2e-sr.pth
use_clustering: False